name: Go

on:
  push:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push to GitHub Container Registry
      uses: docker/build-push-action@v2
      with:
        context: ./backend
        platforms: linux/amd64
        push: true
        tags: ghcr.io/gotti/nginx-static:${{ env.GIT_SHA }}


